name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils
        
    - name: Clone RT-N56U Repository
      run: |
        cd /opt
        sudo git clone https://bitbucket.org/padavan/rt-n56u.git

    - name: Build Toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./clean_sources
        sudo ./build_toolchain

    - name: Prepare Firmware Build
      run: |
        cd /opt/rt-n56u/trunk
        # Make config changes
        echo 'CONFIG_TOOLCHAIN_DIR=/opt/rt-n56u/toolchain-mipsel' >> .config
        echo 'CONFIG_FIRMWARE_PRODUCT_ID="RT-N65U"' >> .config
        # Uncomment the specific line
        sed -i 's/#CONFIG_FIRMWARE_PRODUCT_ID="RT-N56U"/CONFIG_FIRMWARE_PRODUCT_ID="RT-N65U"/' .config

    - name: Clean Source Tree
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree

    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./build_firmware

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: /opt/rt-n56u/trunk/images/*.bin  # Specify your firmware file path
