name: Build RT-N56U Firmware
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build in Docker
      uses: docker://ubuntu:xenial
      with:
        args: |
          bash -c "
          # 更新系统并安装必需的工具和依赖项
          apt-get update && \
          apt-get install -qy apt-utils locales && \
          locale-gen --no-purge en_US.UTF-8 && \
          apt-get install -qy \
              git \
              sudo \
              kmod \
              p7zip-full \
              build-essential \
              gawk \
              pkg-config \
              gettext \
              automake \
              autoconf \
              autopoint \
              libtool \
              bison \
              flex \
              zlib1g-dev \
              libgmp3-dev \
              libmpfr-dev \
              libmpc-dev \
              texinfo \
              mc \
              libncurses5-dev \
              nano \
              vim \
              gperf \
              python-docutils && \
          # 克隆源代码仓库
          git clone https://github.com/h8820/rt-n56u-old.git /opt/rt-n56u && \
          cd /opt/rt-n56u/toolchain-mipsel && \
          sh dl_toolchain.sh && \
          # 创建输出目录
          mkdir -p /opt/images/ && \
          # 构建固件
          cd /opt/rt-n56u/trunk && \
          TNAME=YK-L1 && \
          if [ ! -f configs/templates/$TNAME.config ] ; then \
            echo 'configs/templates/$TNAME.config not found '; \
            exit 1; \
          fi && \
          cp -f configs/templates/$TNAME.config .config && \
          sudo ./clear_tree && \
          sudo ./build_firmware_modify $TNAME 0 && \
          sudo mv -f images/*.trx /opt/images/
          "

    - name: Upload packages
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
